[package]
name = "gatekeeper"
version = "0.1.4"
edition = "2021"

[features]
default = []
live_net = []

[dependencies]
async-trait = "0.1"
clap = { version = "4.6.1", features = ["derive"] }
env_logger = "0.11.10"
openssl = { version = "0.10.80", features = ["vendored"] }
pingora = { version = "0.8.0", features = ["lb", "openssl"] }

[dev-dependencies]
reqwest = "0.13.4"
socket2 = "0.5"
tokio = { version = "1.52.3", features = ["test-util"] }
